language: python
python:
  - "3.6.5"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - ./code-assessment.sh
  - docker run --rm -ti --name zalenium -p 4444:4444 \
    --privileged dosel/zalenium start
  - docker-compose up -d
  - ./test-assessment.sh
