language: python
python:
  - "3.6.5"
services:
  - docker
before_install:
  - curl -sSL https://raw.githubusercontent.com/dosel/t/i/p | bash -s start
  - docker-compose up -d
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - ./code-assessment.sh
  - ./tests-assesment.sh
